dist: xenial
sudo: true
language: python
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - 3.7
install:
  - pip install tox-travis
script:
  - pip install https://github.com/devpi/devpi/archive/master.zip
  - tox
